# Generated by Django 5.0.3 on 2024-03-19 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaning',
            name='word',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meaning', to='app.word'),
        ),
    ]
