# Generated by Django 5.0.3 on 2024-03-27 10:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_synonym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antonym',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('synonym', models.TextField()),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antonym', to='app.word')),
            ],
        ),
    ]
